import type { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className='relative flex h-screen w-screen items-center justify-center overflow-hidden bg-background-foreground text-black'>
            <div className='absolute -bottom-9 -left-16 size-40 rounded-full bg-lavender-mist md:size-64 lg:size-80'></div>
            <div className='absolute -right-20 -top-36 size-80 rounded-full bg-light-cyan md:size-[400px] lg:size-[500px]'></div>
            <Suspense>{children}</Suspense>
        </div>
    );
}
