import type {Metadata} from "next";
import {Suspense} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen bg-background-foreground text-black relative w-screen overflow-hidden flex justify-center items-center">
      <div className="lg:size-80 md:size-64 size-40 rounded-full bg-lavender-mist absolute -left-16 -bottom-9"></div>
      <div className="lg:size-[500px] md:size-[400px] size-80 rounded-full bg-light-cyan absolute -right-20 -top-36"></div>
      <Suspense>{children}</Suspense>
    </div>
  );
}
